services:
  connector:
    build: ./app
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    env_file:
      - .env
  db:
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

    
volumes:
  postgres_data:



  
  
