FROM python:3.12-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

RUN apk update && apk add postgresql-client 

COPY . .
#postgres client to access from inside container


CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
